---
grails:
    profile: web
    codegen:
        defaultPackage: lemato
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html: 
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            rss: application/rss+xml
            text: text/plain
            hal: 
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory' 
        
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password:

environments:
    development:
        dataSource:
            dbCreate: update
            url: jdbc:h2:file:data/lemato;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            dbCreate: update
            url: jdbc:h2:file:data/lemato.prod;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED

grails:
    controllers:
        upload:
            maxFileSize:    8192000
            maxRequestSize: 8192000

elasticsearch:
    cluster:
        name: lemato_cluster        
        url: http://localhost 
        port: 9200 
#        url: https://60fdd65f98b2c5dd530b8796955059c5.eu-west-1.aws.found.io
#        port: 9243        
    template:
        name: lemato_template
        prefix: lemato_*
    response:
        size: 1000
    client:
        mode: node # ('transport', 'node'])
    transport:
#        clusterId: https://60fdd65f98b2c5dd530b8796955059c5
        clusterId: lemato_cluster
        enableSsl: true
        sniff: false # boolean
        user: testadmin:testadmin

es:
    path: 
        home: /Users/martin/Documents/University/Master/Masterarbeit/grails/LeMATo

lemato:
    concordancer: 
        fragment:
            size: 80
    clustering:
        clusterLinkage: MEDIAN_LINKAGE # http://fozziethebeat.github.io/S-Space/apidocs/ Enum HierarchicalAgglomerativeClustering.ClusterLinkage
        simType: EUCLIDEAN # http://fozziethebeat.github.io/S-Space/apidocs/ Enum Similarity.SimType
    scripts:
        directory: esScripts
